### ISSUE TITLE
txAVLPredicate causes an inner priority inversion in the tx queue

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal-Garage/libudpard#32]
Frames are prioritized based on the transfer ID here with no respect for their session ID. This condition is not actually needed because AVL ordering is stable -- items that compare equal retain FIFO ordering

https://github.com/OpenCyphal-Garage/libudpard/blob/32ff7e94b6f8a5f57c6c5722f80043e4be8ccd87/libudpard/udpard.c#L395C23-L410

**Comment by thirtytwobits** [comment]
Does this affect libcanard too?

**Comment by pavel-kirienko** [comment]
no
