### ISSUE TITLE
Set up continuous integration and static analysis

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal-Garage/libudpard#5]
- [x] Run all tests in GitHub Actions.
- [x] Run Clang-Tidy during build.
- [x] Run MISRA compliance checks in SonarCloud.
- [x] Enforce source formatting.
- [x] Upgrade container to ts22.4.3 and fix compiler warnings
- [x] Generate code coverage and upload to SonarCloud

**Comment by SchoberMJ** [comment]
Good call-outs! 
Are there any example packages, manuals, or guides that we should be using as reference to set these up?

**Comment by pavel-kirienko** [comment]
I think libcanard is a good starting point as it includes all of these. I can create a new project for libudpard on SonarCloud, or I could make you an admin there if you prefer.
